# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Neo Amphibian - Java

on:
  push:
    branches: [ "master", "dev_24" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-youtube-selenium-java-tests:
    name: Ubuntu - Test Youtube - Selenium Java
    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install with Maven
      run: mvn clean install -DskipTests
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Test with Maven
      run: mvn clean test verify
    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports-ubuntu
        path: Results/*
        retention-days: 1

  generate-cucumber-report:
    name: Generate Cucumber Report
    runs-on: ubuntu-latest
    if: always()
    needs: [ ubuntu-youtube-selenium-java-tests ]
    steps:
    - name: Download Artifacts from Ubuntu
      uses: actions/download-artifact@v4
      id: download-ubuntu
      with:
        name: cucumber-reports-ubuntu
        path: cucumber-reports-ubuntu

